FROM oven/bun:1.2.18 AS build
WORKDIR /usr/src/app

COPY package.json bun.lock ./
COPY shared ./shared
COPY indexer ./indexer

RUN bun install

FROM oven/bun:1.2.18 AS release
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

COPY --from=build /usr/src/app/indexer ./indexer
COPY --from=build /usr/src/app/shared ./shared

WORKDIR /usr/src/app/indexer
RUN bun run build

ENV NODE_ENV=production
EXPOSE 3001
ENTRYPOINT ["bun", "start"]
